const Map<String, dynamic> PHONEME_REHAB_DATA = {
  'level_2': [
    // --- ZONA ALTA (6kHz–8kHz): Sibilantes e Fricativas Agudas (S/F, S/Z, S/CH) ---
    {'target': 'Sala', 'distractor': 'Fala', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Saca', 'distractor': 'Faca', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sino', 'distractor': 'Fino', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sina', 'distractor': 'Fina', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Selo', 'distractor': 'Zelo', 'freq_band': 8000, 'type': 'voiced_fricative'},
    {'target': 'Cela', 'distractor': 'Vela', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Cacho', 'distractor': 'Caço', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Cesta', 'distractor': 'Festa', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Soco', 'distractor': 'Foco', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sopa', 'distractor': 'Copa', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Faca', 'distractor': 'Vaca', 'freq_band': 4000, 'type': 'fricative'},
    {'target': 'Sumo', 'distractor': 'Fumo', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Caça', 'distractor': 'Casa', 'freq_band': 8000, 'type': 'sibilant'},
    {'target': 'Acho', 'distractor': 'Aço', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Sela', 'distractor': 'Tela', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Cedo', 'distractor': 'Fedo', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sede', 'distractor': 'Fede', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sete', 'distractor': 'Fete', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Soro', 'distractor': 'Foro', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Suar', 'distractor': 'Fuar', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sujo', 'distractor': 'Fujo', 'freq_band': 6000, 'type': 'fricative'},
    {'target': 'Secar', 'distractor': 'Fechar', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Sinal', 'distractor': 'Final', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Senha', 'distractor': 'Fenha', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Saída', 'distractor': 'Faída', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Seco', 'distractor': 'Feco', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Soar', 'distractor': 'Foar', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Serro', 'distractor': 'Ferro', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Sabão', 'distractor': 'Fabão', 'freq_band': 8000, 'type': 'fricative'},
    {'target': 'Saber', 'distractor': 'Faber', 'freq_band': 8000, 'type': 'fricative'},

    // --- ZONA MÉDIA (3kHz–5kHz): Plosivas, Labiodentais, Velares e Transições ---
    {'target': 'Tia', 'distractor': 'Pia', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Chave', 'distractor': 'Trave', 'freq_band': 4000, 'type': 'plosive'},
    {'target': 'Mata', 'distractor': 'Massa', 'freq_band': 8000, 'type': 'sibilant'},
    {'target': 'Vila', 'distractor': 'Fila', 'freq_band': 4000, 'type': 'labiodental'},
    {'target': 'Casa', 'distractor': 'Caça', 'freq_band': 8000, 'type': 'voiced_fricative'},
    {'target': 'Gato', 'distractor': 'Pato', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Dado', 'distractor': 'Tato', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Bala', 'distractor': 'Pala', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Dedo', 'distractor': 'Teto', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Vento', 'distractor': 'Bento', 'freq_band': 3000, 'type': 'fricative_plosive'},
    {'target': 'Jato', 'distractor': 'Gato', 'freq_band': 4000, 'type': 'postalveolar'},
    {'target': 'Gelo', 'distractor': 'Galo', 'freq_band': 750, 'type': 'vowel_contrast'},
    {'target': 'Vaca', 'distractor': 'Faca', 'freq_band': 4000, 'type': 'fricative'},
    {'target': 'Rosa', 'distractor': 'Roça', 'freq_band': 8000, 'type': 'voiced_sibilant'},
    {'target': 'Pote', 'distractor': 'Bote', 'freq_band': 1000, 'type': 'plosive'},
    {'target': 'Cola', 'distractor': 'Gola', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Pinto', 'distractor': 'Tinto', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Mala', 'distractor': 'Mola', 'freq_band': 750, 'type': 'vowel_contrast'},
    {'target': 'Pomba', 'distractor': 'Bomba', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Toca', 'distractor': 'Doca', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Fio', 'distractor': 'Vio', 'freq_band': 4000, 'type': 'labiodental'},
    {'target': 'Bolo', 'distractor': 'Polo', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Dama', 'distractor': 'Tama', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Caro', 'distractor': 'Garo', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Pena', 'distractor': 'Bena', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Telha', 'distractor': 'Delha', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Vida', 'distractor': 'Fida', 'freq_band': 4000, 'type': 'labiodental'},
    {'target': 'Boca', 'distractor': 'Poca', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Dois', 'distractor': 'Tois', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Garra', 'distractor': 'Carra', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Tijolo', 'distractor': 'Dijolo', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Vela', 'distractor': 'Bela', 'freq_band': 3000, 'type': 'labiodental'},
    {'target': 'Tosse', 'distractor': 'Dosse', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Pulo', 'distractor': 'Bulo', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Gola', 'distractor': 'Cola', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Farda', 'distractor': 'Varda', 'freq_band': 4000, 'type': 'labiodental'},
    {'target': 'Cabo', 'distractor': 'Gabo', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Passo', 'distractor': 'Basso', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Toco', 'distractor': 'Doco', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Veio', 'distractor': 'Feio', 'freq_band': 4000, 'type': 'labiodental'},
    {'target': 'Boné', 'distractor': 'Poné', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Terra', 'distractor': 'Derra', 'freq_band': 3000, 'type': 'plosive'},
    {'target': 'Cama', 'distractor': 'Gama', 'freq_band': 1500, 'type': 'velar'},
    {'target': 'Porta', 'distractor': 'Borta', 'freq_band': 1000, 'type': 'bilabial'},
    {'target': 'Dia', 'distractor': 'Tia', 'freq_band': 3000, 'type': 'plosive'},

    // --- ZONA MÉDIA-ALTA (5kHz–6kHz): Mistura de sibilantes e plosivas ---
    {'target': 'Chão', 'distractor': 'São', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Xale', 'distractor': 'Sale', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Chuva', 'distractor': 'Suva', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Cheiro', 'distractor': 'Seiro', 'freq_band': 6000, 'type': 'sibilant'},
    {'target': 'Jogar', 'distractor': 'Chocar', 'freq_band': 4000, 'type': 'postalveolar'},
    {'target': 'Jeito', 'distractor': 'Cheito', 'freq_band': 4000, 'type': 'postalveolar'},
    {'target': 'Janela', 'distractor': 'Zanela', 'freq_band': 4000, 'type': 'postalveolar'},
    {'target': 'Jugo', 'distractor': 'Zugo', 'freq_band': 4000, 'type': 'postalveolar'},

    // --- EXPANSÃO CLÍNICA: Contrastes de Vozeamento, Modo e Nasais ---
    {'target': 'Pata', 'distractor': 'Bata', 'freq_band': 1000, 'type': 'voiced_unvoiced_bilabial'},
    {'target': 'Pato', 'distractor': 'Bato', 'freq_band': 1000, 'type': 'voiced_unvoiced_bilabial'},
    {'target': 'Tio', 'distractor': 'Dio', 'freq_band': 3000, 'type': 'voiced_unvoiced_alveolar'},
    {'target': 'Tanto', 'distractor': 'Danto', 'freq_band': 3000, 'type': 'voiced_unvoiced_alveolar'},
    {'target': 'Cada', 'distractor': 'Gada', 'freq_band': 1500, 'type': 'voiced_unvoiced_velar'},
    {'target': 'Cato', 'distractor': 'Gato', 'freq_band': 1500, 'type': 'voiced_unvoiced_velar'},
    {'target': 'Fila', 'distractor': 'Vila', 'freq_band': 4000, 'type': 'voiced_unvoiced_labiodental'},
    {'target': 'Mato', 'distractor': 'Nato', 'freq_band': 250, 'type': 'nasal'},
    {'target': 'Mula', 'distractor': 'Nula', 'freq_band': 250, 'type': 'nasal'},
    {'target': 'Mola', 'distractor': 'Nola', 'freq_band': 250, 'type': 'nasal'},
    {'target': 'Mapa', 'distractor': 'Napa', 'freq_band': 250, 'type': 'nasal'},
    {'target': 'Pata', 'distractor': 'Mata', 'freq_band': 1000, 'type': 'stop_nasal'},
    {'target': 'Bata', 'distractor': 'Mata', 'freq_band': 1000, 'type': 'stop_nasal'},
    {'target': 'Tia', 'distractor': 'Mia', 'freq_band': 3000, 'type': 'stop_nasal'},
    {'target': 'Gala', 'distractor': 'Nala', 'freq_band': 1500, 'type': 'stop_nasal'},
  ]
};
